spring:
  main:
    allow-bean-definition-overriding: true
  application: 
    name: mg-compose-uauth
  session: 
    timeout: 3600s
    redis: 
      namespace: 
        spring: session
      flushmode: on_save
    storetype: redis
  servlet: 
    multipart: 
      resolvelazily: true
      maxrequestsize: 6000MB
      location: "c:/tmp"
      filesizethreshold: 2000
      maxfilesize: 6000MB
  redis: 
    host: 127.0.0.1
    port: 6379
    database: 0
server: 
  port: 129
hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 5000
        timeout: 
          enabled: true
eureka: 
  client: 
    serviceurl: 
      defaultZone: "http://127.0.0.1:81/eureka"
  instance:
    prefer-ip-address: true

ribbon:
  ConnectTimeout: 3000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  ReadTimeout: 3000
  OkToRetryOnAllOperations: false
logging: 
  level: 
    root: info
  file: ../mg.log/mg.api.uauth.log
feign: 
  hystrix: 
    enabled: true

curator:
  retryCount: 5  #重试次数
  elapsedTimeMs: 5000   #重试间隔时间
  connectString: 10.0.127.235:2181   # zookeeper 地址
  sessionTimeoutMs: 60000  # session超时时间
  connectionTimeoutMs: 5000  # 连接超时时间